// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listJobs(status: string | null) : Promise<Result<Job[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_jobs", { status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getJob(id: string) : Promise<Result<Job | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_job", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createJob(input: CreateJobInput) : Promise<Result<Job, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_job", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateJob(id: string, input: UpdateJobInput) : Promise<Result<Job, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_job", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteJob(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_job", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Verify a VAP manifest and import it as a tracked job. Never submits.
 */
async importPacket(input: ImportPacketInput) : Promise<Result<ImportPacketResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_packet", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listFollowups(status: string | null) : Promise<Result<Followup[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_followups", { status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listFollowupsForJob(jobId: string) : Promise<Result<Followup[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_followups_for_job", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFollowup(input: CreateFollowupInput) : Promise<Result<Followup, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_followup", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateFollowup(id: string, input: UpdateFollowupInput) : Promise<Result<Followup, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_followup", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFollowup(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_followup", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listNotesForJob(jobId: string) : Promise<Result<Note[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_notes_for_job", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNote(id: string) : Promise<Result<Note | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createNote(input: CreateNoteInput) : Promise<Result<Note, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_note", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateNote(id: string, input: UpdateNoteInput) : Promise<Result<Note, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_note", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteNote(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getApplicationsByWeek() : Promise<Result<WeeklyApplications[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_applications_by_week") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPipelineFunnel() : Promise<Result<PipelineFunnel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pipeline_funnel") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getResponseRate() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_response_rate") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvgDaysToResponse() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_avg_days_to_response") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSubmissionsByAdapter() : Promise<Result<AdapterCount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_submissions_by_adapter") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTierComparison() : Promise<Result<TierComparison, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_tier_comparison") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSidebarCounts() : Promise<Result<SidebarCounts, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sidebar_counts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProfile() : Promise<Result<Profile | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_profile") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertProfile(input: UpsertProfileInput) : Promise<Result<Profile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_profile", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startSidecar() : Promise<Result<SidecarStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_sidecar") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopSidecar() : Promise<Result<SidecarStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_sidecar") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkSidecarHealth() : Promise<Result<SidecarStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_sidecar_health") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSidecarStatus() : Promise<Result<SidecarStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sidecar_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the per-session submit token for the app's own webview. Reachable only
 * over Tauri IPC (the desktop app), never from another local process.
 */
async getSubmitToken() : Promise<string> {
    return await TAURI_INVOKE("get_submit_token");
},
async storeCredential(key: string, value: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("store_credential", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCredential(key: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_credential", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCredential(key: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_credential", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateFilePath(path: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_file_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async revealInFinder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_in_finder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AdapterCount = { adapter: string; count: number }
/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null; 
/**
 * SHA-256 fingerprint of the ApplyKit signing key trusted for packet imports.
 * If None, imports still verify integrity but do not assert provenance.
 */
applykit_public_key_id: string | null }
export type CreateFollowupInput = { job_id: string; scheduled_date: string; recipient_email: string | null }
export type CreateJobInput = { company: string; role: string; ats: string; apply_url: string; status: string | null; tier: string | null; job_posting_id: string | null; board_token: string | null; source: string | null; resume_path: string | null; cover_letter_path: string | null; custom_fields: string | null; notes: string | null; salary_range: string | null; location: string | null; jd_url: string | null }
export type CreateNoteInput = { job_id: string; note_type: string; title: string; content: string }
export type Followup = { id: string; job_id: string; draft_subject: string | null; draft_body: string | null; status: string; scheduled_date: string; sent_at: string | null; gmail_message_id: string | null; recipient_email: string | null; created_at: string }
export type ImportPacketInput = { 
/**
 * Absolute path to the packet's `packet.manifest.json`.
 */
manifest_path: string; 
/**
 * The posting URL the human is applying to (the packet does not carry it).
 */
apply_url: string; 
/**
 * ATS identifier for the posting (e.g. `ashby`, `greenhouse`, `linkedin`).
 */
ats: string; 
/**
 * Optional trusted signing-key fingerprint. When set, packets not signed by
 * exactly this key are refused (provenance pinning).
 */
expected_public_key_id: string | null }
export type ImportPacketResult = { job: Job; packet_id: string; truth_status: string; stale_artifacts: string[]; 
/**
 * True when a valid Ed25519 signature was present and verified.
 */
signed: boolean; 
/**
 * Signing key fingerprint, if the manifest carried a signature.
 */
public_key_id: string | null }
export type Job = { id: string; company: string; role: string; ats: string; apply_url: string; job_posting_id: string | null; board_token: string | null; status: string; tier: string; source: string | null; resume_path: string | null; cover_letter_path: string | null; custom_fields: string | null; notes: string | null; applied_at: string | null; follow_up_date: string | null; response_date: string | null; salary_range: string | null; location: string | null; jd_url: string | null; 
/**
 * VAP provenance: the source packet's application-identity id (if imported).
 */
source_packet_id: string | null; 
/**
 * VAP provenance: the source packet's manifest schema version (e.g. `vap/1`).
 */
source_packet_version: string | null; 
/**
 * VAP truth status at import: `verified` | `stale` | `unverified` (None if not imported).
 */
truth_status: string | null; created_at: string; updated_at: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type Note = { id: string; job_id: string; note_type: string; title: string; content: string; created_at: string; updated_at: string }
export type PipelineFunnel = { saved: number; applied: number; interviewing: number; offer: number; rejected: number }
export type Profile = { id: number; first_name: string; last_name: string; email: string; phone: string; linkedin_url: string; location: string; authorized_to_work: boolean; requires_sponsorship: boolean; preferred_name: string | null; base_resume_path: string | null; follow_up_days: number; updated_at: string }
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }
export type SidebarCounts = { followups_due: number; prep_needed: number }
export type SidecarState = "Starting" | "Healthy" | "Unhealthy" | "Stopped" | "Failed"
export type SidecarStatus = { state: SidecarState; pid: number | null; restart_count: number; uptime_seconds: number | null }
export type TierComparison = { tier1: TierStats; tier2: TierStats }
export type TierStats = { applied: number; responded: number; interviewing: number; response_rate: number }
export type UpdateFollowupInput = { draft_subject: string | null; draft_body: string | null; status: string | null; scheduled_date: string | null; sent_at: string | null; gmail_message_id: string | null; recipient_email: string | null }
export type UpdateJobInput = { company: string | null; role: string | null; ats: string | null; apply_url: string | null; status: string | null; tier: string | null; job_posting_id: string | null; board_token: string | null; source: string | null; resume_path: string | null; cover_letter_path: string | null; custom_fields: string | null; notes: string | null; applied_at: string | null; follow_up_date: string | null; response_date: string | null; salary_range: string | null; location: string | null; jd_url: string | null }
export type UpdateNoteInput = { title: string | null; content: string | null }
export type UpsertProfileInput = { first_name: string; last_name: string; email: string; phone: string; linkedin_url: string; location: string | null; authorized_to_work: boolean | null; requires_sponsorship: boolean | null; preferred_name: string | null; base_resume_path: string | null; follow_up_days: number | null }
export type WeeklyApplications = { week: string; tier1_count: number; tier2_count: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
